[package]
name = "line_segment_intersection"
description = "Find the intersection between two 2d line segments"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@ulysse.io>"]
license = "MIT"

[dependencies]
num-traits = "0.1"
